.alphabet <- data.frame(original = c(letters,
                                    LETTERS,
                                    0:9,
                                    "!",
                                    "@",
                                    "#",
                                    "$",
                                    "%",
                                    "^",
                                    "&",
                                    "*",
                                    "(",
                                    ")",
                                    "-",
                                    "_",
                                    "+",
                                    "=",
                                    "`",
                                    "~",
                                    "[",
                                    "]",
                                    "{",
                                    "}",
                                    ";",
                                    ":",
                                    "'",
                                    "<",
                                    ">",
                                    ",",
                                    ".",
                                    "/",
                                    " "),
                       stringsAsFactors = FALSE)
